### PR TITLE
Fix deployment/project urls in Slack integration

### PR DESCRIPTION
**Pull request by briangonzalez**
Slack | deployments | Curri 2019-11-20 16-46-03

### CODE REVIEW

**Comment by briangonzalez** [comment]
Let me know when you think this might land @javivelasco and we'd be happy to test over here!

**Comment by briangonzalez** [comment]
@javivelasco Any movement here?

**Comment by paulogdm** [comment]
My apologies for the delay @briangonzalez. We will get this moving.

**Comment by nkzawa** [comment]
@briangonzalez So sorry for the delay but we released it. It looks great, thank you!

**Pull request merged**
